### ISSUE TITLE
Stasis Spell

### ISSUE THREAD

**Issue by Jackbedead** [RealmsMud/RealmsCode#105]
There should be a stasis effect. While this spell is in effect the target cannot move magically - no teleport, track, or word of recall.

You could use it defensively to keep enemies from word of recalling you, use it on a pk target that’s cornered, or wear a powerful item and risk not being able to escape from battle.

**Comment by Jackbedead** [comment]
MP cost: 30
School:  Translocation
Domain:  Travel

This spell ceases all forms of translocation. The target feels their corporal form stranded in a single position, unable to move magically from its current location. This spell keeps adventurers from leaving compromised portions as well as allowing assassins to trap cornered prey. This prevents people under its spell from using word-of-recall abilities.

Syntax:
cast stasis <target>

**Comment by jcdevs** [comment]
Isn't that what anchor does?

**Comment by Jackbedead** [comment]
Would a wand of anchor work for this effect? I'd like an assassin to cast this to keep a target from word-of-recall, without the other anchor abilities.

**Comment by ocelot134269** [comment]
Anchor has been fixed to do this now.
