### ISSUE TITLE
Smith Resizing

### ISSUE THREAD

**Issue by Jackbedead** [RealmsMud/RealmsCode#120]
resize [armor] [smith]

The smith says, "No problem! I'll get to work resizing that piece of armor to fit you."

When a player has a smith resize armor they need a certain level, and only a master smith can resize from small to large. For every size difference, it cost more. If the smith fails, the item loses 10% of its durability and is returned to you. It costs as much as a full repair. The item retains all of its magical effects.

Armor is resized to fit the character that asked for it. This will make the command much easier for players, and reduce abuse. 

I possible, we could also have smiths who specialize in cloth, leather, scale, ring, chain, and plate be necessary for resizing armor of that type. Keep in mind miscellaneous items can also be sized, which could be resized.

**Comment by ocelot134269** [comment]
Will be re-addressed at a later date.
