### ISSUE TITLE
wimpy needs to persist through log off/on

### ISSUE THREAD

**Issue by ocelot134269** [RealmsMud/RealmsCode#156]
Right now there's no way to see what wimpy is set at without doing pref wimpy and toggling it off. And you set wimpy with pref.
Needs to just be a wimpy command, and wimpy by itself shows what it's set at, and you set the wimpy value with that command also.
Doing set wimpy or pref wimpy should just toggle wimpy on and off.

**Comment by ocelot134269** [comment]
Actually, never mind. Right now can do "pref -combat" to see what wimpy is set to.
All that's needed is to make wimpy persist through log off/on.

**Comment by jcdevs** [comment]
Mine are all persisting through log off
