### ISSUE TITLE
initial config files

### ISSUE THREAD

**Issue by prool** [RealmsMud/RealmsCode#20]
Hi!

I successfully make binary file under Ubuntu 16.10 x86_64.

To start the server, me need initial config files. Where can I get them? The old version is not works: rohonline.net/source/realms.initial.zip

With best regards, Serge Prool

**Comment by mitchej123** [comment]
It's been a while since I've looked at those, try this maybe? http://www.mudbytes.net/files/2882/

**Comment by prool** [comment]
Thank You!

I managed to start the MUD server!
