### ISSUE TITLE
Durability Command

### ISSUE THREAD

**Issue by Jackbedead** [RealmsMud/RealmsCode#87]
Players can type "durability" to see a list of currently equipped items with a status bar of their durability based on a percent of total.

durability
You see your currently equipped items.
On body:   some dragonscale armor [=======   ]
On arms:   some xornskin sleeves [=======   ]
On legs:   some xornskin leggings [=====         ]
On neck:   a leather witch-hunter's cloak [=======   ]
In Hand:   a cold iron hook-dagger [====          ]
Shield:    a radiant duelist's buckler [=                 ]
Wielded:   a crystal gladius [====          ]

**Comment by jcdevs** [comment]
I'm adding this to the existing `equipment` command unless someone has a problem with that for some reason.

**Comment by ocelot134269** [comment]
might be useful to put in a new set/clear preference for it. Could default to on.

**Comment by jcdevs** [comment]
Closing this as it has been implemented and is currently in review.
