### ISSUE TITLE
Fix Cleric Dodge and Update Kamira

### ISSUE THREAD

**Issue by Jackbedead** [RealmsMud/RealmsCode#95]
Currently, Kamira clerics dodge based on Piety, and dexterity isn't used at all. Because the most thematic races for Kamira are exclusively +dex races (halflings and soon kenku), and the only class that can become Arachnus is Dark Elves, which are also +2 dexterity, I think it would be more thematic and more intuitive to change their dodge bonus from Pie, to (Pie bonus)+Dex.

This would bring them in line with other clerics, who already receive 2+Dex for their dodge. So, this actually makes them capable of dodging better, rather than dodging worse, than other Clerics. Which is what was intended, I believe.

Line 867
https://github.com/RealmsMud/RealmsCode/blob/master/combat/combatSystem.cpp

**Old way**
chance += (piety.getCur() * .05);

**New way**
chance += ((bonus(player->piety.getCur()) + (dexterity.getCur() * .05));

Also, take a look at line 874. Shouldn't that be the same as 857? It looks like the +2 is added before the percentage is calculated. Are clerics dodging incorrectly?
https://github.com/RealmsMud/RealmsCode/blob/master/combat/combatSystem.cpp

**Comment by jcdevs** [comment]
If you already know technical requirements and can write the code, I'd say just open a pull request with your proposed changes. It can be discussed and approved/denied there

**Comment by Jackbedead** [comment]
I'm not a dev, so I doubt anything I run would compile. I'm not sure if I need that arrow, or if it could just be:  bonus(piety.getCur()) 

My only concern with this change is that it would drop the dodge rate of some Kamira clerics who have already used dexterity as their dump stat, maybe as much as 14% dodge to 10% dodge. 

If we don't want to use the bonus stat number, as we have been moving away from it, we could use pie stat *.02. For instance: 

chance += ((piety.getCur() * .02) + (dex.getCur() * .05));

The overall change is that clerics would continue to get 2+(dex*.05), while Kamira/Arachnus dodge would scale with pie and dex, replacing the flat 2+ with a dynamic number based on piety, ((pie*.02)+(dex*.05)).

**Comment by ocelot134269** [comment]
This is not an issue. Clerics of Kamira already have a luck ability that allows them a chance to be automatically missed by attacks.
