### ISSUE TITLE
Vampires

### ISSUE THREAD

**Issue by Jackbedead** [RealmsMud/RealmsCode#99]
It's been brought up a few times playing recently that vampires/purebloods are having a hard time, and are falling behind pretty severely after 30. I know there are plans to redo a lot of the classes and the idea of making vampires an affliction, but I wanted to put forward some ideas to help them now that I don't think would be difficult to implement.

Upgrade their armor from leather to chain.
Allow bite to drain MP as well as HP.
Give them powers in darkness, rather than be stuck on a day/night cycle.
The class gives infravision to races that don't have it. <-this feels like it should have always been a class benefit, and should be part of the affliction if it's implemented.

I know class changes aren't a priority, and vampires are probably at the bottom along with wolves and monks. But leveling to 30 takes a lot of time, and it's rough when your class falls off. Thanks!

**Comment by ocelot134269** [comment]
This isn't an issue for github. It's more game-related philosophical than technical in nature.
Go open up a discussion on the RoH Forum.
